export async function sync() {
  const items = [
    [
      "Senior React developer for a fintech dashboard",
      4800,
      ["React", "TypeScript", "Figma"],
      "Germany",
      12,
      "fixed",
    ],
    [
      "Build a modern SaaS platform with Next.js",
      6500,
      ["Next.js", "React", "PostgreSQL"],
      "United States",
      8,
      "fixed",
    ],
    [
      "E-commerce redesign · fashion & lifestyle",
      3200,
      ["Figma", "UI/UX", "Shopify"],
      "United Kingdom",
      24,
      "fixed",
    ],
    [
      "Backend engineer — API & integrations",
      4200,
      ["Node.js", "PostgreSQL", "REST API"],
      "Netherlands",
      16,
      "fixed",
    ],
    [
      "React dashboard for a logistics startup",
      2800,
      ["React", "Tailwind CSS", "Charts"],
      "Sweden",
      7,
      "fixed",
    ],
    [
      "Brand identity and website for an architecture studio",
      1900,
      ["Branding", "Webflow", "Figma"],
      "France",
      31,
      "fixed",
    ],
    [
      "Full-stack developer for an internal team portal",
      55,
      ["React", "Node.js", "Docker"],
      "Canada",
      9,
      "hourly",
    ],
    [
      "Landing page development from Figma",
      1200,
      ["React", "CSS", "Figma"],
      null,
      null,
      "fixed",
    ],
    [
      "Build a modern SaaS platform with Next.js",
      6500,
      ["Next.js", "React", "PostgreSQL"],
      "United States",
      8,
      "fixed",
    ],
  ];
  return items.map((x, i) => ({
    platform: "mock",
    external_id: "studio-" + i,
    url: null,
    title: x[0],
    description:
      "Демонстрационное объявление Mock Studio. Команда ищет специалиста для проектирования и реализации продукта. Требуется аккуратная работа с интерфейсом, понятная архитектура и регулярная коммуникация. Результат — готовое приложение с документацией и передачей исходного кода.",
    budget: x[1],
    currency: "USD",
    skills: x[2],
    geography: x[3],
    responses: x[4],
    payment_type: x[5],
    client: {
      name: ["Northstar Studio", "Forma Labs", "Atelier Digital"][i % 3],
    },
    published_at: new Date(Date.now() - (i + 1) * 3600000).toISOString(),
    source_status: "open",
  }));
}
